// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS9dbgnOjsvNbv22Wiy7my2-9IboUQtXI',
    appId: '1:638460786906:web:cb6bda4ac72680befc4de3',
    messagingSenderId: '638460786906',
    projectId: 'feira-facil-a0037',
    authDomain: 'feira-facil-a0037.firebaseapp.com',
    storageBucket: 'feira-facil-a0037.firebasestorage.app',
    measurementId: 'G-J3J11B0GMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjAYDJuUyQ8fZ4JGCJNkR1nFm_IN7Vb9o',
    appId: '1:638460786906:android:f3ca06c74a74c7ddfc4de3',
    messagingSenderId: '638460786906',
    projectId: 'feira-facil-a0037',
    storageBucket: 'feira-facil-a0037.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe8pIfKOe7Ki1zh60f6n0RtsoQGgkY9rQ',
    appId: '1:638460786906:ios:92f4c6957655fcaefc4de3',
    messagingSenderId: '638460786906',
    projectId: 'feira-facil-a0037',
    storageBucket: 'feira-facil-a0037.firebasestorage.app',
    iosBundleId: 'com.feirafacil.feiraFacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe8pIfKOe7Ki1zh60f6n0RtsoQGgkY9rQ',
    appId: '1:638460786906:ios:92f4c6957655fcaefc4de3',
    messagingSenderId: '638460786906',
    projectId: 'feira-facil-a0037',
    storageBucket: 'feira-facil-a0037.firebasestorage.app',
    iosBundleId: 'com.feirafacil.feiraFacil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS9dbgnOjsvNbv22Wiy7my2-9IboUQtXI',
    appId: '1:638460786906:web:10ec742c4ebde95bfc4de3',
    messagingSenderId: '638460786906',
    projectId: 'feira-facil-a0037',
    authDomain: 'feira-facil-a0037.firebaseapp.com',
    storageBucket: 'feira-facil-a0037.firebasestorage.app',
    measurementId: 'G-C5LH3JP0TS',
  );
}
